# Generated by Django 4.0.4 on 2022-08-01 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
                ('gender', models.CharField(choices=[('F', 'female'), ('M', 'male')], default=0, max_length=1)),
                ('yearNumber', models.IntegerField(default=0)),
                ('family', models.IntegerField(default=None)),
                ('area', models.CharField(choices=[('N', '北'), ('C', '中'), ('S', '南')], max_length=2)),
                ('wish1', models.CharField(choices=[('NM', '北弟'), ('NF', '北妹'), ('CM', '中弟'), ('CF', '中妹'), ('SM', '南弟'), ('SF', '南妹')], default=None, max_length=2)),
                ('wish2', models.CharField(choices=[('NM', '北弟'), ('NF', '北妹'), ('CM', '中弟'), ('CF', '中妹'), ('SM', '南弟'), ('SF', '南妹')], default=None, max_length=2)),
                ('wish3', models.CharField(choices=[('NM', '北弟'), ('NF', '北妹'), ('CM', '中弟'), ('CF', '中妹'), ('SM', '南弟'), ('SF', '南妹')], default=None, max_length=2)),
            ],
        ),
    ]
