# Generated by Django 4.0.4 on 2022-08-02 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
                ('gender', models.CharField(choices=[('F', 'female'), ('M', 'male')], default=0, max_length=1)),
                ('yearNumber', models.IntegerField(default=0)),
                ('area', models.CharField(choices=[('N', '北'), ('C', '中'), ('S', '南')], max_length=2)),
                ('high_school', models.CharField(blank=True, default=None, max_length=20)),
                ('wish1', models.CharField(blank=True, choices=[('NM', '北弟'), ('NF', '北妹'), ('CM', '中弟'), ('CF', '中妹'), ('SM', '南弟'), ('SF', '南妹')], default=None, max_length=2, null=True)),
                ('wish2', models.CharField(blank=True, choices=[('NM', '北弟'), ('NF', '北妹'), ('CM', '中弟'), ('CF', '中妹'), ('SM', '南弟'), ('SF', '南妹')], default=None, max_length=2, null=True)),
                ('wish3', models.CharField(blank=True, choices=[('NM', '北弟'), ('NF', '北妹'), ('CM', '中弟'), ('CF', '中妹'), ('SM', '南弟'), ('SF', '南妹')], default=None, max_length=2, null=True)),
            ],
            options={
                'unique_together': {('name', 'yearNumber')},
            },
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fID', models.IntegerField()),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drawing.student')),
            ],
            options={
                'unique_together': {('fID', 'component')},
            },
        ),
    ]
