# Generated by Django 4.0.4 on 2022-08-01 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drawing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='high_school',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
