# Generated by Django 4.0.4 on 2022-08-01 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drawing', '0002_student_high_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='family',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='wish1',
            field=models.CharField(blank=True, choices=[('NM', '北弟'), ('NF', '北妹'), ('CM', '中弟'), ('CF', '中妹'), ('SM', '南弟'), ('SF', '南妹')], default=None, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='wish2',
            field=models.CharField(blank=True, choices=[('NM', '北弟'), ('NF', '北妹'), ('CM', '中弟'), ('CF', '中妹'), ('SM', '南弟'), ('SF', '南妹')], default=None, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='wish3',
            field=models.CharField(blank=True, choices=[('NM', '北弟'), ('NF', '北妹'), ('CM', '中弟'), ('CF', '中妹'), ('SM', '南弟'), ('SF', '南妹')], default=None, max_length=2, null=True),
        ),
    ]
