# Generated by Django 4.0.4 on 2022-08-01 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drawing', '0003_alter_student_family_alter_student_wish1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='family',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='high_school',
            field=models.CharField(blank=True, default=None, max_length=20),
        ),
    ]
